routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts.layout');
});

App::setLocale("es");
Auth::routes();
Route::auth();

Route::post('login2','App\Http\Controllers\Auth\LoginController@Login')->name('login2');
Route::group(['middleware' => 'auth'], function () {

    Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');
    Route::get('/', function () {
             return Redirect::to(route('home'));    
    });

    

Route::resources([
   'usuarios' => 'App\Http\Controllers\Configurar\UsuariosController',
   'marca' => 'App\Http\Controllers\Configurar\MarcaController',
   'modelo' => 'App\Http\Controllers\Configurar\ModeloController',
   'ubicacion' => 'App\Http\Controllers\Configurar\UbicacionController'
  ]);
   
  Route::post('estados/actualizar','App\Http\Controllers\Configurar\EstadosController@actualizar')->name('estados.actualizar');
    Route::post('estados/eliminar','App\Http\Controllers\Configurar\EstadosController@eliminar')->name('estados.eliminar');

    Route::post('marca/actualizar','App\Http\Controllers\Configurar\MarcaController@actualizar')->name('marca.actualizar');
    Route::post('marca/eliminar','App\Http\Controllers\Configurar\MarcaController@eliminar')->name('marca.eliminar');
    Route::post('modelo/actualizar','App\Http\Controllers\Configurar\ModeloController@actualizar')->name('modelo.actualizar');
    Route::post('modelo/eliminar','App\Http\Controllers\Configurar\ModeloController@eliminar')->name('modelo.eliminar');  
});    

app/Http/Controllers/Configurar/EstadosController.php
<?php

namespace App\Http\Controllers\Configurar;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Estados;
use App\Equipos;
use Auth;

class EstadosController extends Controller
{
      public function __construct()
    {
      $this->middleware('auth');
    }
    public function index()
    {
      $estados = Estados::orderby('descripcion','asc')->get();
      return view('Configurar.Estados.index',compact('estados'));
    }
    public function create()
    {

    }
    public function show($id)
    {

    }
    public function store(Request $request)
    {
      $descripcion = $request["descripcion"];
       if($descripcion!='')
       {
        $Estadoss = Estados::where('descripcion',$descripcion)->first();
        if($Estadoss!=null)
        {
          \Session::flash('mensajeError', 'Estados Ya Registrado');
        }else{
          $Estados = new Estados;
          $colortexto  = $request["texto"];
          $colorfondo  = $request["fondo"];        
          $Estados->descripcion = $descripcion;
          $Estados->color_fondo = $request["color_fondo"];
          $Estados->color_texto = $request["color_texto"];         
          $Estados->id_usuario = Auth()->id();
          $Estados->save();
          \Session::flash('mensaje', 'Estado Registrado');
        }
       }
       return redirect()->route('estados.index');
    }
    public function update(Request $request, $id)
    {
       
    }
    
    public function actualizar(Request $request)
    {
      $id = $request["id"];
      $descripcion = $request["descripcion"];
      $colortexto  = $request["color1"];
      $colorfondo  = $request["color2"];
      $Estadoss = Estados::where('id',$id)->first();
      if($Estadoss!=null)
      {
        if($Estadoss->descripcion!=$descripcion){
          $zEstados = Estados::where('descripcion',$descripcion)->first();
          if($zEstados!=null)
          {
             $data["status"]="fallo";
             toastr()->error('Estado No Actualizado');
          }
        }else{
                $Estadoss->descripcion = $descripcion;
          $Estadoss->color_fondo = $colorfondo;
          $Estadoss->color_texto = $colortexto;
          $Estadoss->save();
          $data["status"]="ok";
          toastr()->success('Estado Actualizado');
        }
      }
      

      return $data;
    }

    public function destroy($id)
    {

    }

    public function eliminar(Request $request)
    {
      $id = $request["id"];
      $Estadoss=Estados::where('id',$id)->first();
      if($Estadoss!=null)
      {
        $equipos=Equipos::where('id_estado',$id)->get();
        if($equipos->count()>0)
        {
          $data["status"]="no";
          toastr()->error('Estado no se puede Eliminar');
        }else
        {
          $data["status"]="si";
          $Estadoss->destroy($id);
          
          toastr()->success('Estado Eliminado');
        }
      }
      return $data;
    }
}

app/Http/Controllers/Configurar/MarcaController.php
<?php

namespace App\Http\Controllers\Configurar;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Marcas as Marca;
use App\Models\Modelos as Modelo;
use Auth;

class MarcaController extends Controller
{
      public function __construct()
    {
      $this->middleware('auth');
    }
    public function index()
    {
      $marcas = Marca::orderby('descripcion','asc')->get();
      return view('Configurar.Marca.index',compact('marcas'));
    }
    public function create()
    {

    }
    public function show($id)
    {

    }
    public function store(Request $request)
    {
      $descripcion = $request["descripcion"];
       if($descripcion!='')
       {
        $Marcas = Marca::where('descripcion',$descripcion)->first();
        if($Marcas!=null)
        {
          \Session::flash('mensajeError', 'Marca Ya Registrado');
        }else{
          $Marca = new Marca;
          $Marca->descripcion = $descripcion;
          $Marca->id_usuario = Auth()->id();
          $Marca->save();
          \Session::flash('mensaje', 'Marca Registrado');
        }
       }
       return redirect()->route('marca.index');
    }
    public function update(Request $request, $id)
    {
       
    }
    
    public function actualizar(Request $request)
    {
      $id = $request["id"];
      $descripcion = $request["descripcion"];
      $Marcas = Marca::where('id',$id)->first();
      if($Marcas!=null)
      {
        $zMarca = Marca::where('descripcion',$descripcion)->first();
        if($zMarca!=null)
        {
          $data["status"]="fallo";
          toastr()->error('Marca No Actualizado');
        }else{
          $Marcas->descripcion = $descripcion;
          $Marcas->save();
          $data["status"]="ok";
          toastr()->success('Marca Actualizado');
        }
      }

      return $data;
    }

    public function destroy($id)
    {

    }

    public function eliminar(Request $request)
    {
      $id = $request["id"];
      $Marcas=Marca::where('id',$id)->first();
      if($Marcas!=null)
      {
        $modelo=Modelo::where('id_marca',$id)->get();
        if($modelo->count()>0)
        {
          $data["status"]="no";
          toastr()->error('Marca no se puede Eliminar');
        }else
        {
          $data["status"]="si";
          $Marcas->destroy($id);
          
          toastr()->success('Marca Eliminado');
        }
      }
      return $data;
    }
}

app/Http/Controllers/Configurar/ModeloController.php
<?php

namespace App\Http\Controllers\Configurar;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Modelo;
use App\Equipos;
use App\Marca;
use Auth;

class ModeloController extends Controller
{
      public function __construct()
    {
      $this->middleware('auth');
    }
    public function index()
    {
      $modelos = Modelo::join('marca as a','a.id','=','modelo.id_marca')->select('modelo.id','modelo.descripcion','a.descripcion as marca','modelo.created_at')->orderby('descripcion','asc')->get();
      $marcas = Marca::orderby('descripcion','asc')->get();
      return view('Configurar.Modelo.index',compact('modelos','marcas'));
    }
    public function create()
    {

    }
    public function show($id)
    {

    }
    public function store(Request $request)
    {
      $descripcion = $request["descripcion"];
       if($descripcion!='')
       {
        $modelos = Modelo::where('descripcion',$descripcion)->first();
        if($modelos!=null)
        {
          \Session::flash('mensajeError', 'modelo Ya Registrado');
        }else{
          $modelo = new Modelo;
          $modelo->descripcion = $descripcion;
          $modelo->id_marca   = $request["id_marca"];
          $modelo->id_usuario = Auth()->id();
          $modelo->save();
          \Session::flash('mensaje', 'modelo Registrado');
        }
       }
       return redirect()->route('modelo.index');
    }
    public function update(Request $request, $id)
    {
       
    }
    
    public function actualizar(Request $request)
    {
      $id = $request["id"];
      $descripcion = $request["descripcion"];
      $modelos = Modelo::where('id',$id)->first();
      if($modelos!=null)
      {
        $zmodelo = Modelo::where('descripcion',$descripcion)->first();
        if($zmodelo!=null)
        {
          $data["status"]="fallo";
          toastr()->error('modelo No Actualizado');
        }else{
          $modelos->descripcion = $descripcion;
          $modelos->save();
          $data["status"]="ok";
          toastr()->success('modelo Actualizado');
        }
      }

      return $data;
    }

    public function destroy($id)
    {

    }

    public function eliminar(Request $request)
    {
      $id = $request["id"];
      $modelos=Modelo::where('id',$id)->first();
      if($modelos!=null)
      {
        $equipos=Equipos::where('id_modelo',$id)->get();
        if($equipos->count()>0)
        {
          $data["status"]="no";
          toastr()->error('modelo no se puede Eliminar');
        }else
        {
          $data["status"]="si";
          $modelos->destroy($id);
          
          toastr()->success('modelo Eliminado');
        }
      }
      return $data;
    }
}

app/Http/Controllers/Configurar/UbicacionController.php
<?php

namespace App\Http\Controllers\Configurar;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Ubicacion;
use App\Equipos;
use Auth;

class UbicacionController extends Controller
{
      public function __construct()
    {
      $this->middleware('auth');
    }
    public function index()
    {
      $ubicacions = Ubicacion::orderby('descripcion','asc')->get();
      return view('Configurar.Ubicacion.index',compact('ubicacions'));
    }
    public function create()
    {

    }
    public function show($id)
    {

    }
    public function store(Request $request)
    {
      $descripcion = $request["descripcion"];
       if($descripcion!='')
       {
        $ubicacions = Ubicacion::where('descripcion',$descripcion)->first();
        if($ubicacions!=null)
        {
          \Session::flash('mensajeError', 'Ubicacion Ya Registrado');
        }else{
          $ubicacion = new ubicacion;
          $ubicacion->descripcion = $descripcion;
          $ubicacion->id_usuario = Auth()->id();
          $ubicacion->save();
          \Session::flash('mensaje', 'Ubicacion Registrada');
        }
       }
       return redirect()->route('ubicacion.index');
    }
    public function update(Request $request, $id)
    {
       
    }
    
    public function actualizar(Request $request)
    {
      $id = $request["id"];
      $descripcion = $request["descripcion"];
      $ubicacions = Ubicacion::where('id',$id)->first();
      if($ubicacions!=null)
      {
        $zubicacion = Ubicacion::where('descripcion',$descripcion)->first();
        if($zubicacion!=null)
        {
          $data["status"]="fallo";
          toastr()->error('ubicacion No Actualizado');
        }else{
          $ubicacions->descripcion = $descripcion;
          $ubicacions->save();
          $data["status"]="ok";
          toastr()->success('ubicacion Actualizado');
        }
      }

      return $data;
    }

    public function destroy($id)
    {

    }

    public function eliminar(Request $request)
    {
      $id = $request["id"];
      $ubicacions=Ubicacion::where('id',$id)->first();
      if($ubicacions!=null)
      {
        $equipos=Equipos::where('id_ubicacion',$id)->get();
        if($equipos->count()>0)
        {
          $data["status"]="no";
          toastr()->error('ubicacion no se puede Eliminar');
        }else
        {
          $data["status"]="si";
          $ubicacions->destroy($id);
          
          toastr()->success('ubicacion Eliminado');
        }
      }
      return $data;
    }
}

resources/views/Configurar/Usuarios/cambiarp.blade.php
@extends ('layouts.layout')
@section('titulo', 'Cambiar contraseña')
@section('link_back',route("usuarios.index"))
@section('link_new_none','d-none')

@section('content')
@if(Session::has('mensaje'))
<div class="alert alert-info alert-dismissible fade show" role="alert">
    <span class="alert-icon"><i class="ni ni-like-2"></i></span>
    <span class="alert-text"><strong>Éxito</strong> {!!Session::get('mensaje')!!}</span>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif
@if(Session::has('mensajeError'))

<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <span class="alert-icon"><i class="ni ni-like-2"></i></span>
    <span class="alert-text"><strong>Error!!</strong>  {!!Session::get('mensajeError')!!}</span>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif
<div class="row">
<div class="col-12 grid-margin stretch-card">

<div class="card">
                <div class="card-body">

<form role="form" action="{{ route('usuarios.update_password', $usuario->id) }}" method="POST">
    {{ csrf_field() }}
    {{ method_field('PUT') }}

        <div class="col-lg-6">
            <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                <label>Clave ({{ $usuario->name }})</label>
                <input type="password" class="form-control" name="password" maxlength="100" required>
                @if ($errors->has('password'))
                    <p class="help-block">{{ $errors->first('password') }}</p>
                @endif
            </div>
        </div>
        <div class="col-lg-6">
            <div class="form-group">
                <label>Confirmar Clave</label>
                <input type="password" class="form-control" name="password_confirmation" maxlength="100" required>
            </div>
        </div>
    </div>
     <div class="card-footer">
        <button type="submit" class="btn btn-success">
            <i class="fa fa-fw fa-check"></i> Guardar</button>
        </div>
     
</form>
</div>
</div>
</div>




@endsection
@section('javascript')
    <script type="text/javascript">
        $(document).ready(function(){
            setTimeout(function(){
                $(".alert").slideUp(500);
            },3000)
        })
    </script>
@endsection

resources/views/Configurar/Usuarios/edit.blade.php
@extends ('layouts.layout')
@section('titulo', 'Editar Usuario')
@section('link_back',route("usuarios.index"))
@section('link_new_none','d-none')
@section('content')
<div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong>{{ __('Modificar Usuario') }}</strong> - Complete todos los campos
            </div>
            @if ( count( $errors ) > 0 )
                <div class="alert  alert-danger alert-dismissible fade show" role="alert">
                    <span class="badge badge-pill badge-danger">AVISO:</span> 
                        @foreach ($errors->all() as $error)
                            {{ $error }} <br>
                        @endforeach
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
            @endif
            <div class="card-body card-block">
                <form action="{{ route('usuarios.update',$user->id) }}" method="POST" enctype="multipart/form-data" class="form-horizontal">
    {{ csrf_field() }}
    {{ method_field('PUT') }}
                <div class="row form-group">
                    <div class="col col-md-3">
                        <label class=" form-control-label">{{ __('Correo Electrónico') }}</label>
                    </div>
                    <div class="col-12 col-md-9">
                        <p class="form-control-static">{{$user->email}}</p>
                    </div>
                </div>
                <div class="row form-group">
                        <div class="col col-md-3"><label for="email-input" class=" form-control-label">{{ __('Nombre') }}</label></div>
                        <div class="col-12 col-md-9"><input value="{{$user->name}}" placeholder="Nombre del Usuario" id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>
                            <small class="help-block form-text">Porfavor ingresa el nombre del usuario</small></div>
                </div>                
                <div class="row form-group">
                    <div class="col col-md-3"><label for="select" class=" form-control-label">{{ __('Rol de Usuario') }}</label></div>
                    <div class="col-12 col-md-9">
                    <select id="role_id_select" class="form-control" name="role_id" required>
                        <option value="">Seleccione</option>
                        @foreach($roles as $role)
                        @if ($user->role_id==$role->id)
                        <option value="{{$role->id}}" selected="selected">{{$role->description}}</option>
                        @else
                        <option value="{{$role->id}}">{{$role->description}}</option> 
                        @endif                        
                        @endforeach                       
                    </select>                                    
                    </div>
                </div>
            </div>
                <div class="card-footer">
                        <button type="submit" class="btn btn-success btn-sm">
                        <i class="fa fa-refresh"></i> {{ __('Modificar') }}
                        </button>
                        <button type="reset" class="btn btn-warning btn-sm">
                            <i class="fa fa-undo"></i> {{__('Restaurar')}}
                        </button>
                    </div>
                </form>
        </div>
        </div>
@endsection

resources/views/Configurar/Usuarios/index.blade.php
 @extends ('layouts.layout')
 @section('titulo', 'Usuarios')
 @section('link_back',route("home"))
 @section('link_new',route('usuarios.create'))

 @section('content')   
 @if(Session::has('mensaje'))

<div class="alert alert-info alert-dismissible fade show" role="alert">
    <span class="alert-icon"><i class="ni ni-like-2"></i></span>
    <span class="alert-text"><strong>Éxito</strong> {!!Session::get('mensaje')!!}</span>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif
@if(Session::has('mensajeError'))

<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <span class="alert-icon"><i class="ni ni-like-2"></i></span>
    <span class="alert-text"><strong>Error!!</strong>  {!!Session::get('mensajeError')!!}</span>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif
<div class="row">
 <div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">     
            <div class="table-responsive">
          <table class="table table-striped data-table">
            <thead>
              <tr>
                <th>Usuario</th>
                <th>Correo Electrónico</th>
                <th>Rol</th>
                <th>Creado</th>
                <th>Status</th>
                <th>Acciones</th>
              </tr>
            </thead>
            <tbody>
              @foreach($usuarios as $usuario)
              <tr>
                <td>{{ $usuario->name }}</td>
                <td>{{ $usuario->email }}</td>
                <td>{{ $usuario->description }}</td>
                <td>{{ $usuario->created_at}}</td>
                <td>
                             @if($usuario->id_estado==1)
                             <div class="col">
                                <p class="mb-2">Activo</p>
                                <label class="toggle-switch toggle-switch-success">
                                 <input type="checkbox" id="status" name="status" data-id="{{$usuario->id}}" checked="">
                                  <span class="toggle-slider round"></span>
                                  </label>                      
                             </div>
                             @else
                             <div class="col">
                        <p class="mb-2">Deshabilitado</p>
                      <label class="toggle-switch toggle-switch-dark">
                        <input type="checkbox" id="status" name="status" data-id="{{$usuario->id}}">
                        <span class="toggle-slider round"></span>
                      </label>                      
                    </div>
                   @endif
                  
                </td>
                <td class="td-actions">
                  <a class="btn btn-success btn-sm" href="{{ route('usuarios.edit',$usuario->id) }}" title="Editar Registro">
                              <i class="typcn typcn-edit btn-icon-append"></i>                          
                            </a>

                    <?php 
                    $valor = $usuario->id; 
                    $url="usuarios/cambiar/".$valor; ?>
                    <a data-toggle="tooltip" data-placement="top" class="btn btn-info btn-sm" href="{{ url($url) }}" title="Cambiar Contraseña"><i class="mdi mdi-account-key"></i></a>

              {{--     @switch($usuario->id_estado)
                      @case(1)


                      <a style="font-size: 1.2rem" type="button" rel="tooltip" title="Remover" href="{{ route('usuarios.estatus',$usuario->id)}}" class="btn btn-danger btn-sm">
                        <i class="mdi mdi-account-off "></i>
                    </a>
                          @break
                      @case(0)
                      <a style="font-size: 1.2rem" type="button" rel="tooltip" title="Activar" href="{{ route('usuarios.estatus',$usuario->id)}}" class="btn btn-warning btn-sm">
                        <i class=" mdi mdi-account-check "></i>
                    </a>
                          @break
                      @case(2)
                       <a style="font-size: 1.2rem" type="button" rel="tooltip" title="Activar" href="{{ route('usuarios.estatus',$usuario->id)}}" class="btn btn-warning btn-sm">
                        <i class=" mdi mdi-account-check "></i>
                    </a>
                    </button>
                          @break

                      @default                          
                  @endswitch  --}}              
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
 </div> 
@endsection
@push('scripts')
<script>
  
$(document).ready(function() {
  $('#status').on('click', function(e){
    id = $(this).data('id');
    console.log(id);
  estaSeleccionado = $('input:checkbox[name=status]:checked').val();
    if(estaSeleccionado == 'on') activo = 1;
    else activo = 0;
  

  $.ajaxSetup({
    headers: {
      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
  });
  url="usuarios/estatus";
  $.ajax({
    type: "post",
    url: url,
    dataType: "json",
    cache: false,
    data: {id: id},
    success: function (data){
      console.log(data);
      location.reload();          
    }
  });


   });  
   
} );
  $(function () {

    

    var table = $('.data-table').DataTable({

      "language": {
      "url": "https://cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
    },      

    });

    

  });  

</script>

@endpush

resources/views/Configurar/Usuarios/register.blade.php
@extends ('layouts.layout')
@section('titulo', 'Crear Usuario')
@section('link_back',route("usuarios.index"))
@section('link_new_none','d-none')

@section('content')
<div class="col-md-12">
<div class="card">
    <div class="card-header">
        <strong>{{ __('Nuevo Usuario') }}</strong> - Complete todos los campos
    </div>
    @if ( count( $errors ) > 0 )
                <div class="alert  alert-danger alert-dismissible fade show" role="alert">
                    <span class="badge badge-pill badge-danger">AVISO:</span> 
                        @foreach ($errors->all() as $error)
                            {{ $error }} <br>
                        @endforeach
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
            @endif
    <div class="card-body card-block">
        <form action="{{ route('usuarios.store') }}" method="POST" enctype="multipart/form-data" class="form-horizontal">
                    @csrf
        <div class="row form-group">
                <div class="col col-md-3"><label for="email-input" class=" form-control-label">{{ __('Nombre') }}</label></div>
                <div class="col-12 col-md-9"><input placeholder="Nombre del Usuario" id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>
                    <small class="help-block form-text">Por favor ingresa el nombre del usuario</small></div>
        </div>
        <div class="row form-group">
                <div class="col col-md-3"><label for="email-input" class=" form-control-label">{{ __('Correo Electrónico') }}</label></div>
                <div class="col-12 col-md-9">
                    <input placeholder="Correo Electrónico" id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required autocomplete="email">
                </div>
        </div>
        <div class="row form-group">
            <div class="col col-md-3"><label for="select" class=" form-control-label">{{ __('Rol de Usuario') }}</label></div>
            <div class="col-12 col-md-9">
            <select id="role_id" class="form-control" name="role_id" required>
                <option value="">Seleccione</option>
                @foreach($roles as $role)
                <option value="{{$role->id}}">{{$role->description}}</option>
                @endforeach                        
            </select>                
            </div>
        </div>
        <div class="row form-group">
            <div class="col col-md-3"><label for="password-input" class=" form-control-label">{{ __('Clave') }}</label></div>
            <div class="col-12 col-md-9">
                <input placeholder="Clave"  id="password" type="password" class="form-control" name="password" required autocomplete="new-password">                        
            </div>            
        </div>
        <div class="row form-group">
            <div class="col col-md-3"><label for="password-input" class=" form-control-label">{{ __('Confirmación Clave') }}</label></div>
            <div class="col-12 col-md-9">
                    <input placeholder="Confirmación Clave" id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">               
                <small class="help-block form-text">Por favor repita la contraseña</small></div>
        </div>
    </div>
        <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-sm">
                <i class="fa fa-dot-circle-o"></i> {{ __('Registrar') }}
                </button>
                <button type="reset" class="btn btn-danger btn-sm">
                <i class="fa fa-ban"></i> Borrar
                </button>
            </div>
        </form>
</div>
</div>
@endsection